// Vidya Campus SMS — Supabase connection config
const SUPABASE_URL = 'https://xdzrygsajqljjwdgxqag.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhkenJ5Z3NhanFsamp3ZGd4cWFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODYxMzc3MTEsImV4cCI6MjEwMTcxMzcxMX0.6h8az5C1nU3xQ15EWOJX7UY0owmakdQPmHUv6LLRE_c';
